name: Build and Release

on:
  push:
    tags:
      - "v*" # This will trigger on any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build and Zip for Windows
        run: bun run compile:win

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist.zip
          path: ./dist.zip

  release:
    needs: build
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.0 # Updated version
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use your PAT here
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## ${{ github.ref_name }}

            ### What's Included
            - Windows build (dist.zip)

            ### Build Information
            - Build Date: ${{ steps.current_time.outputs.time }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref }}

            ### Installation
            - Download the Zip
            - Extract
            - Open the executable

            ### Notes
            - Don't move the executable away from the ./dist/ folder.
            - Please report any issues or bugs on our GitHub issue tracker.
            - For full changes, please refer to the commit history.

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2 # Updated version
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
